Externa links validation
EveripediaNetwork/ep-api pull request #100
Opened 2022-05-04 19:07 UTC by philipep-galdino

# Externa links validation

_Now we validate links that are in the wiki content so we won't allow external links other than our own links. It gets the links from the .env which reads the value 'everipedia.org/', so we don't really need to change it from the alpha/dev for the actual production - I will add it in the server! so it checks if the link in the wiki content is our own or not, if not, the wiki gets invalidated._

## How should this be tested?

1. Create a wiki with links
2. Run indexer service (if locally)
3. Check logs for the validation
4. Re-run the same with external links other than our own.

## Notes or observations

_I had a small problem with nestjs and .envs as usual 😅 that's the reason of the late time of delivery for this. but it's done before closing on one more day and kinda of still on the time! XD_

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/301

2022-05-04 21:29 UTC, kesar commented
be strict about the url. the includes could be easily bypassed w someone creating any random domain that includes everipedia.org

2022-05-04 21:40 UTC, AshakaE commented
> be strict about the url. the includes could be easily bypassed w someone creating any random domain that includes everipedia.org

That's correct, but is it possible for anyone other than everipedia to use `everipedia.org` ?

2022-05-04 21:42 UTC, AshakaE requested changes

2022-05-04 21:42 UTC, AshakaE commented on src/Indexer/Validator/validator.service.ts
> +      const uiLink = this.configService.get('UI_URL')
Kindly add the `.sample.env` 👍

2022-05-05 09:19 UTC, kesar commented
> > be strict about the url. the includes could be easily bypassed w someone creating any random domain that includes everipedia.org
> 
> That's correct, but is it possible for anyone other than everipedia to use `everipedia.org` ?

using includes in the code means that https://cesar-evil.com/?url=everipedia.org w pass that security check

also cesar-everipedia.org would pass it

2022-05-05 09:20 UTC, kesar commented
has this being tested? im wondering if this library checks links in markdown style

2022-05-05 10:39 UTC, philipep-galdino commented on src/Indexer/Validator/validator.service.ts
> +      const uiLink = this.configService.get('UI_URL')
> Kindly add the `.sample.env` +1

thank you for the reminder!

2022-05-05 10:41 UTC, philipep-galdino commented
> > > be strict about the url. the includes could be easily bypassed w someone creating any random domain that includes everipedia.org
> > 
> > 
> > That's correct, but is it possible for anyone other than everipedia to use `everipedia.org` ?
> 
> using includes in the code means that https://cesar-evil.com/?url=everipedia.org will pass that security check
> 
> also cesar-everipedia.org would pass it

I guess that makes sense. My plan in the beginning was to use startsWith('https://alpha.everipedia.org'), that might solve the problem. I'll begin testing these use cases this morning! 👍🏾 🚀  

and answering your questions, yeah! It's been tested, and I believe it does. It checks for links in general content from what I tried out in my tests

2022-05-05 11:03 UTC, kesar commented
but it needs to find links not urls. I mean there is nothing wrong with write www.cesar.cafe in the content but it can't be linked

2022-05-05 11:15 UTC, philipep-galdino commented
> but it needs to find links not urls. I mean there is nothing wrong with write without linking cesar.cafe in the content but it can't be linked
> 
> and yeah, probably we can go w startsWith() + full url as you were proposing in this example 👍🏻

alright, we'll do so! also, about finding links and not urls, the package has a 'isLink' property, which is the one I'm using instead of checking if it's a URL or not. so yeah, I guess it'll work fine - I only tested out with links from now. 

I'll make some more tests before merging this up.

2022-05-06 11:42 UTC, philipep-galdino commented
> in the screenshot the href is wrong so they dont catch properly markdown
> 
> it needs to verify the / bcs otherwise some one can create https://alpha.everipedia.org.cesar.com and bypass the security.
> 
> if we want to accept https://alpha.everipedia.org we can do an exception for that EXACT string but everything else needs to make sure it has proper domain validation

I guess it makes sense that we dont accept the link without '/'. I don't remember how I yesterday did this 
![image](https://user-images.githubusercontent.com/28926336/167124686-4e1429f0-d0a7-4f8a-b471-0cc0f79cc10e.png)

but apparently it's not common anyway. I'm not sure how links works in markdowns but I'll just keep it working with the proper domain validation then! is that ok?

2022-05-09 13:55 UTC, merged