Pm2 server deploy
EveripediaNetwork/ep-api pull request #26
Opened 2022-03-25 22:09 UTC by philipep-galdino

# Improve server deploy with pm2

_Make the server start along with the Indexer service restarting and watching out for the blockchain. Basically now they both start along with pm2._

## How should this be tested?

1. run pm2 restart ecosystem.config.js 
2. run pm2 logs
3. check if the applications are running correctly

## Notes or observations

_I'm having a problem with pm2 on the dev server we have. I can not set it up there to run `pm2 restart ecosystem.config.js`, even after `yarn add global pm2` went well with no errors it says that pm2 command was not found. Is it going to run correctly when deploy? I wanted to test it first._

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/123

2022-03-25 22:10 UTC, philipep-galdino commented
Created directly from the last branch that we set up pm2 just because it's a do-along task, lol. 

check out my doubt over the PR description, please!

2022-03-26 00:36 UTC, kesar commented
https://stackoverflow.com/questions/40317578/yarn-global-command-not-working make sure yarn is exported in zsh / bash

2022-03-28 08:45 UTC, kesar commented on .github/workflows/deploy.yml
> +            pm2 restart ecosystem.config.js
missing the yarn to get latest packages

2022-03-28 08:46 UTC, kesar requested changes
missing yarn install

2022-03-28 11:19 UTC, philipep-galdino commented on .github/workflows/deploy.yml
> +            pm2 restart ecosystem.config.js
yeep, forgot about it! haha done

2022-03-28 11:45 UTC, kesar approved these changes

2022-03-28 18:32 UTC, philipep-galdino commented
so, basically what I'm trying to do is improve how the service runs in the background - pm2 doesn't have such thing as to 'keep it alive', as it by default does keeps the application alive. I ran it on my local and the application was running ok and the indexer service were running and being restarted every 15min. 

what I notice is that I can try to improve how the indexer service is going to be working as instead of setting it on and off every 15min, just keep it on as the application does and restart if anything wrong happens.

I did a little bash script there on the deploy to wait for the application - the error that you told me about indexer service trying to start, failing and then restarting was because of this, the application and the indexer were tried to run side by side when the indexer needs the application on first. 

I still have to try it out on the server itself, tho.

2022-03-28 18:41 UTC, kesar commented on indexer-ecosystem.config.js
> -    {
why remove it from here?

2022-03-28 18:43 UTC, kesar commented
> I did a little bash script there on the deploy to wait for the application - the error that you told me about indexer service trying to start, failing and then restarting was because of this, the application and the indexer were tried to run side by side when the indexer needs the application on first.

Why indexer needs api running? I've been running indexer without API if I dont recall wrong

You need to add --loop true to the indexer to keep it looping without restarting

2022-03-28 19:00 UTC, philipep-galdino commented
> Why indexer needs api running? I've been running indexer without API if I dont recall wrong
> 
> You need to add --loop true to the indexer to keep it looping without restarting

ok, got it. I knew I was forgetting something and there was a overengineering in this lol. 😅  and yeah I totally thought that the indexer was somehow depended to the API. 

I guess I can do it simpler then, let me push the changes

2022-03-29 19:14 UTC, philipep-galdino commented
managed to set yarn global to work on the server. yarn global bin wasn't set, that was the problem. working fine now!

2022-03-29 19:50 UTC, philipep-galdino commented
all done! 

to test all of this;
`pm2 start ecosystem.config.js --only ep-api`
`pm2 status ep-api` then if ready
`pm2 start ecosystem.config.js --only indexer-service`

to check out the whole service running:
`pm2 logs` 
and you'll get both ep-api running along with the indexer-service catching IFPS hashes and logging it out (if there are anym, if not, it'll just keep running until it gets)

2022-03-30 07:31 UTC, kesar approved these changes

2022-03-30 19:32 UTC, merged