Adds linked wikis
EveripediaNetwork/ep-api pull request #276
Opened 2022-12-28 15:56 UTC by Royal-lobster

### [DRAFT]
Related https://github.com/EveripediaNetwork/issues/issues/930

2023-01-03 12:08 UTC, AshakaE requested changes
everything looks good, just some minor changes. 👍

2023-01-03 12:08 UTC, AshakaE commented on src/Database/database.config.ts
> +        LinkedWikis,
- [ ] We won't need this in entities array, it's just an object type

2023-01-03 12:08 UTC, AshakaE commented on src/Database/Entities/linkedWikis.entity.ts
> +export default LinkedWikis
- [ ] Kindly refactor to just a ts file, I think because I also stored media as  `.entity.ts` but it's just a type

2023-01-03 12:18 UTC, Royal-lobster commented on src/Database/database.config.ts
> +        LinkedWikis,
Oh thanks will remove it in a new commit.

2023-01-03 12:18 UTC, Royal-lobster commented on src/Database/Entities/linkedWikis.entity.ts
> +export default LinkedWikis
Oh so the file name is linkedWikis.ts right ? should i also change it for media ?

2023-01-03 12:37 UTC, kesar commented on src/App/notifications/notifications.command.ts
> +          if (status) {
a good improvement will be to add a linter rule to reject PR if they are not following the rules. That will avoid adding LoC of changes that are unrelated to the PR.

Very often we get this in the PR, and thats something we should solve as we do in the ep-ui 👍🏻 

(Not needed to add in this PR, but something it would be great to have)

2023-01-03 13:04 UTC, Softdev1 commented on src/App/notifications/notifications.command.ts
> +          if (status) {
Okay nice

2023-01-03 13:37 UTC, AshakaE commented on src/Database/Entities/linkedWikis.entity.ts
> +export default LinkedWikis
Correct

2023-01-04 09:20 UTC, Royal-lobster commented on src/Database/database.config.ts
> +        LinkedWikis,
Shall i also remove the media from this list ?

2023-01-04 14:16 UTC, AshakaE approved these changes

2023-01-05 14:18 UTC, merged