wiki discord logs
EveripediaNetwork/ep-api pull request #467
Opened 2023-11-06 08:33 UTC by icemedia001

# wiki discord logs

Organizing the logs coming into discord from address -> wiki api, the idea is to show frequency of addresses requested.
For now we can store the data at cache level with 2 hrs ttl

https://github.com/EveripediaNetwork/issues/issues/1907

2023-11-06 09:51 UTC, kesar commented on src/App/Wiki/wiki.service.ts
> +      const cacheKey = 'key'
is it the cacheKey 'key' ?

2023-11-06 09:54 UTC, kesar commented on src/App/Wiki/wiki.service.ts
> +          if (recurringAddresses[address]) {
if u want to simplify all this if / else you could use something like:
```
recurringAddresses[address] = (recurringAddresses[address] || 0) + 1;
```

|| will set to 0 if it doesnt exist

2023-11-13 13:32 UTC, AshakaE requested changes

2023-11-20 07:24 UTC, AshakaE approved these changes

2023-11-20 07:24 UTC, merged