Blog caching
EveripediaNetwork/ep-api pull request #579
Opened 2024-08-28 15:29 UTC by icemedia001

Blog caching

create a simple system using pm2 api that interacts with other processes the idea is to feed each process with the same cache data incase one of the processes get's the cache initially this will help reduce external requests and keep same cache data consistent for each pm2 process

closes https://github.com/EveripediaNetwork/issues/issues/3063

2024-08-30 09:45 UTC, kesar commented on package.json
> +    "@nestjs/core": "^8.3.1",
i dont think this PR needs to upgrade any lib in package.json. revert or explain the reason

2024-08-30 09:45 UTC, kesar commented on src/App/Cache/cache.service.ts
> +      const response = await axios.get('https://')
?

2024-08-30 09:46 UTC, kesar commented on src/App/Cache/cache.service.ts
> +    pm2.connect((err) => {
? whats this? please elaborate

2024-09-09 08:19 UTC, AshakaE requested changes
This service needs an API to serve the result from the blog service, and the result needs to be cached.

I'm also unable to test locally, and there are lint errors.

2024-09-11 08:00 UTC, AshakaE requested changes

2024-09-11 08:00 UTC, AshakaE commented on src/App/Blog/blog.resolver.ts
> +}
Only one resolver is needed to serve that data generated from the blog service

2024-09-11 09:03 UTC, kesar commented on src/App/Blog/blog.dto.ts
> +export class EntryPathOutput {
@AshakaE lets fix codeclimate to avoid these errors. I dont think they are being useful at all

2024-09-11 09:04 UTC, AshakaE commented on src/App/Blog/blog.dto.ts
> +export class EntryPathOutput {
Got it

2024-09-11 11:54 UTC, AshakaE requested changes
I don't see the cache being used

2024-09-11 11:54 UTC, AshakaE commented on src/App/Blog/blog.resolver.ts
> +  ): Promise<
Kindly refactor arguments into one class

2024-09-11 11:54 UTC, AshakaE commented on src/App/Blog/blog.resolver.ts
> +      }
Move the try catch logic into the service class

2024-09-19 10:59 UTC, AshakaE approved these changes

2024-09-19 11:00 UTC, merged