Improve pipeline
EveripediaNetwork/ep-api pull request #62
Opened 2022-04-08 11:38 UTC by philipep-galdino

# Improve deploy pipeline 

_Basically an improve for our deploy pipeline to check for tests and linting errors_

## How should this be tested?

1. Accepting this PR 😅 
2. Then checking the deploy action
3. Another option I'm trying locally is using act. (https://github.com/nektos/act)

## Notes or observations

_I am having a little trouble with 'act' (https://github.com/nektos/act) running so I can test out our actions locally, apparently it has something to do with my bash terminal. I'm checking it out, I think it's better for us to test it like that than having to deploy and then panicking and going back to fix it if it goes wrong XD

another thing I wanted to note! Never did anything with github actions, did all of that based on examples, learning about it on the go and what I saw on our push-checks, heh_

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/126

2022-04-08 12:29 UTC, philipep-galdino commented on .github/workflows/deploy.yml
> +    needs: build
> i think this needs only work if build is a job inside of this pipeline, but I am not sure 100% sure

not actually from what I've seen, buuuut, this was actually a mistake of mine hahahaa, I left it there from the last commit! sorry heh

2022-04-11 08:40 UTC, kesar approved these changes

2022-04-11 11:23 UTC, kesar requested changes
lint, build, test & deploy

this does test lint and deploy

2022-04-11 13:20 UTC, kesar approved these changes

2022-04-13 02:45 UTC, merged