User in activity table
EveripediaNetwork/ep-api pull request #86
Opened 2022-04-27 09:12 UTC by philipep-galdino

# User field Added to Activity table

_Now we have an user field that needs to be filled/registered every time a new activity goes in and so you can get it on a basic Activity query. Also now we have a query to filter Activity by User ID too._

## How should this be tested?

1. Run the API
2. Create a new Wiki 
3. Run graphQL Playground and run the queries for User in Activities or Activities where User ID equals your User ID.

## Notes or observations

_Our new query running along with our new field added to the schema:_
![image](https://user-images.githubusercontent.com/28926336/165484513-8089f320-0f2a-4584-9571-3d3d6a99a380.png)

## Linked issues

closes #00, closes #001, closes https://github.com/EveripediaNetwork/issues/issues/270

2022-04-27 10:52 UTC, AshakaE approved these changes
Looks good 👍

2022-04-27 14:20 UTC, kesar commented on src/Database/Entities/activity.entity.ts
> +  user!: User
I think you will need to fix somehow the current data on the dev api in order to make this mandatory. Probably you need to run some small script / manually add the userId values from the old activities

2022-04-27 16:28 UTC, kesar commented on src/App/activity.resolver.ts
> +      order: {
limit / offset are missing. you are extending PaginationArgs but not using those args

2022-04-28 08:59 UTC, kesar requested changes
limit / offset are missing. you are extending PaginationArgs but not using those args

2022-04-28 18:13 UTC, philipep-galdino commented on src/App/activity.resolver.ts
> +      order: {
alright, done! forgot about that 😅

2022-04-28 18:14 UTC, philipep-galdino commented
@AshakaE came up with a good SQL script to add the userId values from the old activities, once I get the ok here we'll merge and run the script on the db as we need the column there

2022-04-28 20:44 UTC, AshakaE commented
> @AshakaE came up with a good SQL script to add the userId values from the old activities, once I get the ok here we'll merge and run the script on the db as we need the column there

![image](https://media.giphy.com/media/xSM46ernAUN3y/giphy.gif)

2022-04-29 09:31 UTC, kesar approved these changes

2022-04-29 14:16 UTC, merged